SELECT AVG(MAX(salary))
  FROM employees
  GROUP BY department_id;

create table member(
id number generated by default on null as identity,
name varchar2(100) not null,
passwd varchar2(50) not null)
;

select * from member;

select * from tab; // 현재 ace 계정에서 사용할수있는 자원 목록
select * from user_objects; // 사용할수 있는 오브젝트 목록
select * from user_tables;
select * from user_views;
select * from user_sequences;

desc member;